# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/snake.xdc

# IP: D:/vivdo_project/managed_ip_project/managed_ip_project.cache/ip/2021.2/9/f/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: d:/vivdo_project/snake/snake.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/vivdo_project/snake/snake.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/vivdo_project/snake/snake.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
